name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install python-is-python3
        run: sudo apt-get update && sudo apt-get install -y python-is-python3

      - name: Install OpenSCAD nightly
        run: sudo snap install openscad-nightly --edge --devmode

      - name: Install dev requirements
        run: python -m pip install -r requirements-dev.txt

      - name: Init .cache
        run: mkdir -p .cache || true

      - name: Run tests
        run: python -m unittest discover -s tests -p "test_*.py"
